### ISSUE TITLE
Profile Social info issue

### ISSUE THREAD

**Issue by edack** [christinloehner/linuxcounter.new#48]
I entered info in two fields twitter and whatever in next. After saving and then viewing info was in google+ and twitter. Entered info shifted up one position. also google+ was a link that when clicked on sent me to your depressed 404 webserver ?Marvin?.

**Comment by tallship** [comment]
The errors you're experiencing seem to be the result of two bugs that are described in more detail...

Here, as issue #66 : https://github.com/christinloehner/linuxcounter.new/issues/66

And here, as issue #68: https://github.com/christinloehner/linuxcounter.new/issues/68

This bug is 10 months old?

![2016-03-24_1936](https://cloud.githubusercontent.com/assets/561994/14036930/65578de0-f1fb-11e5-9e43-ad4a1f4b4e4e.png)

**Comment by christinloehner** [comment]
#66 and #68 are closed, so this should also be closed now, right?
